server:
  port: 8888

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mysql
    username: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    druid:
      aop-patterns: com.learn.admin
      filters: stat,wall

      stat-view-servlet:
        enabled: true

      web-stat-filter:
        enabled: true
        url-pattern: /*
        exclusions: '*.js,*.gif,*.jpg,*png,*.css,*.ico,/druid/*'
  aop:
    proxy-target-class: true
#热部署生效
spring.devtools.restart.enabled: true



mybatis-plus:
  mapper-locations: classpath:/mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true



#  thymeleaf:
#    prefix: classpath:/templates/  #prefix：指定模板所在的目录
#    check-template-location: true  #check-tempate-location: 检查模板路径是否存在
#    cache: false  #cache: 是否缓存，开发模式下设置为false，避免改了模板还要重启服务器，线上设置为true，可以提高性能。
#    suffix:  .html
#    #encoding: UTF-8
#    #content-type: text/html
